#!/bin/sh

# Start sxhkd if no instance is running
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Zathura state=tiled

bspc config focused_border_color "#ffb52a"

# Start polybar
bash ~/.config/polybar/launch.sh

# Author: Blurgy <gy@blurgy.xyz>
# Date:   Dec 09 2020, 15:32 [CST]
